eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:8761/eureka/
server:
  #当前服务端口号
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/chrywhy/test
              
          searchPaths: spring-cloud/helloworldConfig
          
  application:
    name: config-server